### ISSUE TITLE
RIP Nintendo CEO - Mr Satoru Iwata

### ISSUE THREAD

**Issue by johnrees** [iimarckus/pokered#100]
I know it's not a technically an issue, and I apologise if it's considered spamming the issues... but considering how many hours he must have spent poring over the code that has been liberated in this repository, I thought it was more suitable to leave my sentiments here then in a Facebook post to an audience of mostly non-gamer friends.

I did not know much about the Iwata-san's programming talents before today. For instance, I didn't know that he led the programming on one of my all time favourite games, 'Earthbound'. Or indeed that he was able to decipher the pokemon battle system within a week, and go on to port it for another game in the franchise.

This quote is probably being overused today, but I love the fact that a CEO of one of the world's biggest videogame companies was able to say it-

"On my business card, I am a corporate president. In my mind, I am a game developer. But in my heart, I am a gamer." - Satoru Iwata in his keynote speech at GDC 2005

RIP

https://www.nintendo.co.uk/Iwata-Asks/Iwata-Asks-Pokemon-HeartGold-Version-SoulSilver-Version/Iwata-Asks-Pokemon-HeartGold-Version-SoulSilver-Version/3-Just-Being-President-Was-A-Waste-/3-Just-Being-President-Was-A-Waste--225951.html

http://www.gamefaqs.com/boards/631516-wii-u/65723555

**Comment by NinjaKiwiChip** [comment]
Here, here.

I second this.

**Comment by iimarckus** [comment]
Whatever the sentiment, this really isn’t the place for it. Sorry.
