### ISSUE TITLE
Unable to load fixed ROMX section into bank $1F

### ISSUE THREAD

**Issue by ShinkoNet** [iimarckus/pokered#69]
Trying to build  using cgywin, it comes up with this error.
$ make
rgbasm -h -o red/audio.o red/audio.asm
rgbasm -h -o red/main.o red/main.asm
rgbasm -h -o red/text.o red/text.asm
rgbasm -h -o red/wram.o red/wram.asm
rgblink -n pokered.sym -o pokered.gbc red/audio.o red/main.o red/text.o red/wram.o
: Unable to load fixed ROMX section into bank $1F
Makefile:91: recipe for target 'pokered.gbc' failed
make: *** [pokered.gbc] Error 1

What causes this?

I was able to build Kanzure's version without any errors. (except the fact my modified .asm files would not be applied in the build)

**Comment by dannye** [comment]
That just means you tried to put more than $4000 bytes of stuff into bank $1f.
Bank $1f is originally for music, so if you added some custom songs, you probably used one that's too long and exceeded the $4000 byte limit.

**Comment by ShinkoNet** [comment]
Thanks for the info. I'm able to add in custom music now :)

**Comment by yenatch** [comment]
You might be interested in [Sanqui/pokered-randomizer](https://github.com/Sanqui/pokered-randomizer), whose sound engine has been replaced with Crystal's.

**Comment by Fotomac** [comment]
I'm having the same problem, but with bank $3, and I'm not really sure I added anything into it that would... oh, wait, maybe I do know. Maybe it could be the addition of the Brock rematch on Mt. Moon, or a rearranging of the wild Pokémon, or the addition of a better Old Rod function, all of which I do plan to include in my game, that's causing the problem. So what could I take out of bank $3 that could solve the problem?
