### ISSUE TITLE
Hall of Fame Room handler is incorrect [Music].

### ISSUE THREAD

**Issue by Xanadu16** [iimarckus/pokered#83]
Its supposed to remain the slow Cities1 music from when Oak walks in and talks to Red and Blue, and continue to play despite changing maps.

**Comment by iimarckus** [comment]
pokered does this—it builds to an exact copy of the original Red and Blue ROMs. Maybe you meant to file this bug against a different project?

**Comment by mathiasbynens** [comment]
I guess this issue can be closed as invalid.
