### ISSUE TITLE
Tidy up map connection macros.

### ISSUE THREAD

**Issue by huderlem** [iimarckus/pokered#85]
The map connection macros have constants like `ROUTE_10_HEIGHT - 24`, but that doesn't really capture what the actual value should be.  I'm not sure what the right thing to do is, but it seems like hardcoding the actual value would be better than doing confusing subtraction.

**Comment by yenatch** [comment]
Most of the time strip lengths depend more on the dimensions of the current map.

For Route 9 -> Route 10, you would want `ROUTE_9_HEIGHT + 3`.

**Comment by huderlem** [comment]
Yep, I agree with that.  It's the instances like the one above that can be improved.
