### ISSUE TITLE
Not an issue, but a question. Where is the routine "PrintText"? 

### ISSUE THREAD

**Issue by KairuMKDS** [iimarckus/pokered#97]
I've been looking all over for the routine PrintText. All I want to see is how the game prints the text to the screen in the text box. Thanks if anybody can answer this and sorry for posting this in here.

**Comment by dannye** [comment]
You can grep "PrintText:" or you can search for "PrintText:" in notepad++ by searching in the entire pokered/ directory using the "*.asm" filter. Both methods will show you where the function is located very quickly.

**Comment by dannye** [comment]
In case you were still wondering:
https://github.com/iimarckus/pokered/blob/master/home.asm#L4193

**Comment by KairuMKDS** [comment]
@dannye I get a message when I grep anything: "fatal: Not a git respository (or any of the parent directories): .git

**Comment by dannye** [comment]
That means you did not properly `git clone` the pokered repo.

**Comment by yenatch** [comment]
`grep -r PrintText: .`

**Comment by dannye** [comment]
@KairuMKDS Gonna go ahead and close this. Feel free to pop in the irc if you have any questions.
